spring:
  datasource:
    url: jbc:sqlserver://localhost:5555; databaseName=(nombreDB)
    username:
    password:
    driver-class-name: com.mysql.jdbc

jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.SQLServerDialect
      jbdc:
        time_zone: UTC
